#!/usr/bin/env bash
# Manages manage_my_process script (start, stop, restart)

if [ "$1" == "start" ]
then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "Process started"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
