#!/usr/bin/env bash
# Display "Best School" ten times
# on iteration 9 display "Hi" before "Holberton School"

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( c++ ))
done
