#!/usr/bin/env bash
# Loop from 1 to 10
# Display "bad luck" on iteration 4
# Display "good luck" on iteration 8
# Display "Best School" on other iterations

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 3 ]
	then
		echo "bad luck"
	elif [ $c -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( c++ ))
done
