#!/usr/bin/env bash
# Display numbers from 1 to 20
# Display "bad luck from China" on iteration 4
# Display "bad luck from Japan" on iteration 9
# Display "bad luck from Italy" on iteration 17

c=1

while [ $c -le 20 ]
do
	echo "$c"
	case $c in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( c++ ))
done
